module.exports = {
  days: {
    m: 'Monday',
    tu: 'Tuesday',
    w: 'Wednesday',
    th: 'Thursday',
    f: 'Friday',
    sa: 'Saturday',
    su: 'Sunday',
  },
  types: {
    ac: 'Activity',
    cl: 'Clinical Clerkship',
    co: 'Conference',
    di: 'Discussion',
    fi: 'Final Exam',
    fm: 'Film',
    fw: 'Fieldwork',
    in: 'Independent Study',
    it: 'Internship',
    la: 'Laboratory',
    le: 'Lecture',
    mi: 'Midterm',
    mu: 'Make-up Session',
    ot: 'Other Additional Meeting',
    pb: 'Problem Session',
    pr: 'Practicum',
    re: 'Review Session',
    se: 'Seminar',
    st: 'Studio',
    tu: 'Tutorial',
  },
};
